[package]
name = "intern"
version = "0.1.0"
authors = ["Mark Rousskov <mark.simulacrum@gmail.com>"]
edition = "2021"

[dependencies]
serde = { workspace = true, features = ["derive"] }
hashbrown = { workspace = true }
bumpalo = "3.2"
parking_lot = "0.12"
arc-swap = "1.3"
lazy_static = "1"
